### ISSUE TITLE
[Research needed] mark changed documents 

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#105]
I'm not 100% sure if this is even possible, but it might help if the portal marked documents that differ from the original proposal.

This was a thought I had during the labmeeting, so no real idea how to do this. Maybe compare file checksums?

**Comment by miggol** [comment]
I think that implementing some kind of checksum while working on #98 is feasible. But I also think marking *changed* documents is a bad idea. 

We can't tell if a document was meaningfully changed through a checksum, and marking it as such might frustrate reviewers who went looking for differences. Realistically, all we can say for sure is that the file is completely unchanged since the last revision. We could definitely add that as an annotation, and then check it by means of no new file being uploaded for this revision.

Maybe we can implement this as a custom FileField which saves the refnum of the proposal it was added in? If it's not the current one, we can add an "unchanged" sticker.

Being very pedantic here but I suspect this might save us some complaints.

**Comment by tymees** [comment]
> I think that implementing some kind of checksum while working on #98 is feasible. But I also think marking changed documents is a bad idea.
>
> We can't tell if a document was meaningfully changed through a checksum, and marking it as such might frustrate reviewers who went looking for differences. Realistically, all we can say for sure is that the file is completely unchanged since the last revision. We could definitely add that as an annotation, and then check it by means of no new file being uploaded for this revision.

Yes, it's true that we can only say if it's the same file as before. 

However, realistically the file only changes when there is a good reason. I don't think researchers will change a file in non-meaningfull ways, as they will probably only change it when requested or when think putting in effort is necessary. 

Also, meaningfull is a bit vague. Normally, formatting wouldn't be meaningfull. However, if the committee rejected a proposal because the formatting of text was atrocious, it suddenly becomes meaninfull. Another example would be changed `u` to `je`, which can be both meaningfull and not-meaningfull depending on context. 

Thus, a simple 'hey, this file isn't the same` would be preferable over something more complex, as complexity adds more edge cases. (And edge cases can result in more false positives/negatives). 

> Maybe we can implement this as a custom FileField which saves the refnum of the proposal it was added in? If it's not the current one, we can add an "unchanged" sticker. Do you think that would work?

It would work, but not as well as a checksum check. This would effectively only track if someone uploaded a file in that proposal, even if the researcher uploads the same file as before. At least with a checksum we know it's the same file. 


Alternatively we could do a comparison on the contents, but that would noisy (resulting in false positives/negatives) and would not cover formatting as well. So all in all, while checksums would probably result in confusion if the change is non-obvious, I still think it's simplicity is prefereable. Also, we could simply make VERY clear that we only check if the file is the exact same file.

**Comment by miggol** [comment]
Good points. I'm a bit of a pessimist when it comes to hashing complex file types like word documents. I think just opening a word document changes the hash through author history and autosaving metadata. But admittedly this is based on stuff I've read online and not my own testing. Also this is a lot less likely with PDFs. (though I wouldn't put it past Adobe reader)

My primary qualm with the approach is not hashing but moreso the user experience. I feel like a message that says "this is the same file as last time" is helpful to the reviewer, and encourages common sense on all files which don't have that marker. When we add a "this file has changed" (or a variant with more context) message we're actively pointing a reviewer in its direction which gives them a reason to look for changes. 

I don't have the support experience with the portal to know how likely this truly is, but unless we attach a hashing 101 article, and all reviewers actually read it, I feel like we might cause reviewers to be confused and ask around what the changes were. "If you know it's changed why can't you just tell me what the changes are?" If we only know with about 80% certainty that the contents actually did change I'd rather just say nothing than assert something.

Regardless, it's absolutely true that checksumming is a way more rigorous way to go about this, and therefore preferable, because as you mentioned it would work for the submitter re-uploading the exact same file. Our FileFields could have a CurrentFileHash and a PreviousFileHash, and copy current to previous when a revision is created. Alternately we could have a complete checksum history in a dict to cover A > B > A, but once again I feel like presenting that information might be more confusing than helpful.

**Comment by tymees** [comment]
Hadn't thought of that. I'm not sure how Word metadata is saved, but I do see how that could change the hash. 

However, we shouldn't try to minimize all the potential issues that _might_ arise. (We'd never be done that way). I think it's very unlikely that someone uploads the same document twice *and* Word has changed the metadata in the meantime. 

I don't think it will result in a lot of support work if it does happen, as the number of committee members is relatively small. If it does happen a lot, we can always revisit this issue. 

That being said, switching the message to 'this file is exactly the same' instead of 'this file differs' is a good suggestion!

> Regardless, it's absolutely true that checksumming is a way more rigorous way to go about this, and therefore preferable, because as you mentioned it would work for the submitter re-uploading the exact same file. Our FileFields could have a CurrentFileHash and a PreviousFileHash, and copy current to previous when a revision is created. Alternately we could have a complete checksum history in a dict to cover A > B > A, but once again I feel like presenting that information might be more confusing than helpful.

That would work.

A simpler solution would be storing the hash of the latest file, and just compare that with the parent proposal objects. No need to keep track of multiple hashes if we have the original file (metadata) still in the original proposal. 

A chain of all checksums isn't really necessary, as all users will only see the latest file that was uploaded anyway.

We don't even have to store the checksum in the database, as we can just do that on the fly. (But it might be better to store it anyway, for data integrity and performance reasons).
