### ISSUE TITLE
Use applicant names in Pre-approved and pre-assesment PDF's

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#386]
I just noticed that for a Pre-assessment (and perhaps for regular applications as well) it seems to be possible to fill in solisid's (which sometimes only consist of numbers) in the field 'Uitvoerende(n) (inclusief uzelf)'. This is not desirable; I then have to find out via Outlook who these people are. Can we make it such that names are filled in when selecting a solisid?

**Comment by tymees** [comment]
I'm a bit confused; where aren't you seeing the names?

The field you're pointing to should always contain name and email information, as that field couples applications to solis accounts directly. It sometimes failes to find accounts, that we know, but I've never seen it not finding names for those accounts.

**Comment by tymees** [comment]
Desiree mailed me with some more information.

The problem is that the pre-assessment and pre-approved PDF templates use a rather simple method of listing all the applicants resulting in solis-id's only. 

The regular PDF has a better way of generating that section, so we should just copy over the code
