### ISSUE TITLE
Role secretaris

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#547]
Would it be possible to make a distinction between the role of secretary (who needs to be able to access and handle all applications) and the role of secretary as reviewer? Now I am linked to all applications as reviewer, which makes it difficult to track how many applications I actually assessed. It would be helpful if the workload of the secretary could be made (more) visible (see #545). If I do not assess an application, I now fill in something like: [niet beoordeeld], to make clear I was not involved in the assessment of (this version of) this application.

I think it is okay by default to have the secretary linked to an application as reviewer, but it would be nice if I still had access to a particular application, but could remove myself from the list of reviewers. Would that be possible?

**Comment by tymees** [comment]
> I think it is okay by default to have the secretary linked to an application as reviewer, but it would be nice if I still had access to a particular application, but could remove myself from the list of reviewers. Would that be possible?'

This is already possible? Just remove yourself when assigning reviewers?

It won't show up on your own decision pages, but will under all generic ones (including 'running')

**Comment by tymees** [comment]
Jup, just verified this is possible:
![image](https://github.com/DH-IT-Portal-Development/ethics/assets/7061963/1ec5f166-0765-490b-b745-990945094720)
(Note: admin is not the secretary, 'Ty Mees' is in this example).

We solved this issue ages ago, when the regularly switching of secretaries became a problem (as some applications disappeared into limbo because the secretary couldn't see all applications)

**Comment by djhcapel** [comment]
Thanks Ty! Think we can close this issue then ;-)

**Comment by tymees** [comment]
Okay :)
