### ISSUE TITLE
Allow privileged users access to the archive regardless of faculty

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#610]
Currently access to the archive is denied to members of chambers and even the secretary if they aren't in the humanities faculty. I'm assuming this isn't desirable.

But just to double-check, I'm paging @djhcapel to ask if groups like the AK, LK, and secretaries should actually be given archive access.

**Comment by djhcapel** [comment]
This issue was created because the 'adjunt-secretaris' did not have access to the archive. She will, however, be formally affiliated to GW as of 26 February, so I presume she will then have access to the archive, since she already has the secretary role? 

Further, I assumed all persons with a GW Solis-ID had access to the archives of both LK and AK in the portal? And that only Site-export is visible to those people with the secretary role?
