### ISSUE TITLE
Members: editing of comments

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#638]
In the LC, some of us remembered being able to edit comments. This does not seem possible anymore. One of us inadvertently pressed 'Enter' halfway a sentence, and could not undo that anymore. Could an editing option be re-installed? Or incorporated? Perhaps with a tick that a comment is ready?

**Comment by miggol** [comment]
Short term because this used to be possible, so if we can easily reinstate that feature then great.

However, if it turns out that this feature was removed because of some kind of complexity or bug, this can be moved to the "long term" milestone.

**Comment by tymees** [comment]
The problem was introduced here:
https://github.com/DH-IT-Portal-Development/ethics/commit/c7e2fedc53fdec51c7a5b30be9b737094f2d7641

The first change was restoring old behaviour, it always locked the option after all comments where in (I checked against the v2 tag). The second change locks a decision after a go/no-go is set, which was not in the pre-review-actions code.

**Comment by miggol** [comment]
Well found, Ty.

@djhcapel We'll restore the old behaviour for now: anyone can edit their feedback *unless* they were the final reviewer and the review enters the "To conclude" stage.
